kind: pipeline
name: python-package

clone:
  depth: 50

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: python:3
    commands:
      - pip install --upgrade pip setuptools wheel
      - python setup.py test

  - name: build
    image: python:3
    commands:
      - pip install --upgrade pip setuptools wheel
      - python setup.py bdist_wheel
      - python setup.py sdist --formats=zip

  - name: publish-staging
    image: shocki/alpine-devpi-client
    environment:
      DEVPI_USER:
        from_secret: devpi_user
      DEVPI_PASS:
        from_secret: devpi_password
      DEVPI_SERVER:
        from_secret: devpi_server
    commands:
      - devpi use $DEVPI_SERVER/$DEVPI_USER/staging
      - devpi login $DEVPI_USER --password $DEVPI_PASS
      - devpi upload dist/*.whl
      - devpi upload dist/*.zip

  - name: publish-stable
    image: shocki/alpine-devpi-client
    environment:
      DEVPI_USER:
        from_secret: devpi_user
      DEVPI_PASS:
        from_secret: devpi_password
      DEVPI_SERVER:
        from_secret: devpi_server
    commands:
      - devpi use $DEVPI_SERVER/$DEVPI_USER/stable
      - devpi login $DEVPI_USER --password $DEVPI_PASS
      - devpi upload dist/*.whl
      - devpi upload dist/*.zip
    when:
      event:
        - tag