wrap_errors: true

messaging:
  # the channel our request/response dialog happens on
  reqres: "inproc://turtl-req"
  # the channel used to send events from the core to the UI
  events: "inproc://turtl-events"
  # if true, the reqres channel responses will vary by the message id. so if you
  # set a message id of 53 and this is `true`, and messaging.reqres is
  # "turtl-req" then the response will come back on the channel "turtl-req:53"
  #
  # if this is false, the responses will come back on "turtl-req" and each
  # response message will have a message id you can use to match.
  reqres_append_mid: false

# override w/ runtime config! on desktop this should be a subfolder in the user
# folder. in android it should be the location of the app's data folder.
data_folder: '~/.config/turtlpy'

# logging configuration
logging:
  # the log level (ignore all messages with a log level lower than this)
  level: 'debug'
  # the file to log to. if missing, logging will just be stdout
  file: 'core.log'
  # log rotation, only applies if `logging.file` is set
  rotation:
    keep: 3
    size: 1048576

sync:
  enable_incoming: true
  enable_outgoing: true
  enable_files_incoming: true
  enable_files_outgoing: true
  poll_timeout: 25